### ISSUE TITLE
testnet / staging

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-infra#4]
align the naming convention for our test environment by picking one name

**Comment by bodymindarts** [comment]
Closing in favour of https://github.com/GaloyMoney/galoy-deployments/issues/410

**Comment by bodymindarts** [comment]
FYI this repository has the definition of the generic infra setup that isn't coupled to a specific environment. Its like the 'class' definition.

testnet/staging is a specfic _instance_. The definition of the instances are in galoy-deployments.
